name: BetaVAE_05x10x_01B                                      # Trained on larger 450k dataset
target: ldm.models.wrapper.beta_vae-t2i.BVaeLDMWrapper        # Wrapper to use LDM Autoencder pre-trained model    
params:
  ckpt_path: checkpoints/BetaVAE_0.50x-1.00x-0.1b_last.ckpt   # Select checkpoint path for pre-trained beta-VAE model